# MARKET BASKET ANALYSIS
- Planteamos la siguiente hipotesis de preguntas a resolver:
1. Que items son comprados con mayor frecuencia juntos.
2. Que item es comprado con mayor frecuencia como producto unico.
3. Que oportunidades existe de impulsar una venta cruzada/venta adicional
4. *anything other insights that might help the business (especially the types of findings included typically as part of market basket analysis)*

In [1]:
# main libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# the database is in the form of a csv file, so we will use pandas to read it
df = pd.read_csv("Analytics case study (market basket analysis ecommerce).csv")
df.head()

,Product,Product Category (Enhanced Ecommerce),Transaction ID,Unique Purchases,Product Revenue
0,3.7V 3400mah LIION 12.6WH,Battery/Consumer Rechargeable,EC0043605902,47,"$1,597.53"
1,3V PHOTO LITHIUM,Battery/Primary Other,EC0043507670,47,"$1,246.44"
2,12V 11.2AH 225CCA AGM 12/0,Battery/Powersports,EC0043504182,41,"$4,714.59"
3,12V 12AH 165CCA FLOODED 6/0,Battery/Powersports,EC0043503186,39,"$2,456.61"
4,12V 12AH 210CCA AGM 12/0,Battery/Powersports,EC0043406547,34,"$3,570.00"

In [3]:
# revisamos la composion de la base de datos
# vemos que hay 92250 filas y 5 columnas, y que no hay valores nulos
# observamos el tipo de datos de cada columna y que esta correponda con el tipo de dato que se espera
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92250 entries, 0 to 92249
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Product                                92250 non-null  object
 1   Product Category (Enhanced Ecommerce)  92250 non-null  object
 2   Transaction ID                         92250 non-null  object
 3   Unique Purchases                       92250 non-null  int64
 4   Product Revenue                        92250 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.5+ MB

In [4]:
# revisamos si existen filas duplicadas. 
df.duplicated().sum()

np.int64(0)

In [5]:
# convertimos encabezado a minusculas y cambiamos nombre de columna product category a product_category para evitar problemas de formato.
df.columns = df.columns.str.lower()
df = df.rename(columns={'product category (enhanced ecommerce)': 'product_category'})
df.head()

,product,product_category,transaction id,unique purchases,product revenue
0,3.7V 3400mah LIION 12.6WH,Battery/Consumer Rechargeable,EC0043605902,47,"$1,597.53"
1,3V PHOTO LITHIUM,Battery/Primary Other,EC0043507670,47,"$1,246.44"
2,12V 11.2AH 225CCA AGM 12/0,Battery/Powersports,EC0043504182,41,"$4,714.59"
3,12V 12AH 165CCA FLOODED 6/0,Battery/Powersports,EC0043503186,39,"$2,456.61"
4,12V 12AH 210CCA AGM 12/0,Battery/Powersports,EC0043406547,34,"$3,570.00"

In [6]:
# convermios las filas de  la columna product y product category a minusculas para evitar problemas de formato.
df["product"] = df["product"].str.lower()
df["product_category"] = df["product_category"].str.lower()
df.head()

,product,product_category,transaction id,unique purchases,product revenue
0,3.7v 3400mah liion 12.6wh,battery/consumer rechargeable,EC0043605902,47,"$1,597.53"
1,3v photo lithium,battery/primary other,EC0043507670,47,"$1,246.44"
2,12v 11.2ah 225cca agm 12/0,battery/powersports,EC0043504182,41,"$4,714.59"
3,12v 12ah 165cca flooded 6/0,battery/powersports,EC0043503186,39,"$2,456.61"
4,12v 12ah 210cca agm 12/0,battery/powersports,EC0043406547,34,"$3,570.00"

In [9]:
df['transaction id'].nunique()

83014

In [10]:
df['transaction id'].value_counts()

transaction id
EC0043604442    37
EC0043909841    30
EC0043101877    25
EC0043108851    16
EC0043903687    15
                ..
EC0043600016     1
EC0043509720     1
EC0043509299     1
EC0043508984     1
EC0043708571     1
Name: count, Length: 83014, dtype: int64

In [7]:
df.nunique()

product              2412
product_category       86
transaction id      83014
unique purchases       24
product revenue      5864
dtype: int64